In [25]:
import numpy as np
import h5py
import pandas as pd
import matplotlib.pyplot as plt
import sys
sys.path.append('/home/julub/COMPAS/misc/unsupported_utils')
from compasUtils import printCompasDetails, getEventHistory, getEventStrings

In [38]:
# Import Output file
Data = h5py.File('COMPAS_Output_1/COMPAS_Output.h5', 'r')

SPs = Data['BSE_System_Parameters']
MTs = Data['BSE_RLOF']
CEs = Data['BSE_Common_Envelopes']
SNe = Data['BSE_Supernovae']
DCs = Data['BSE_Double_Compact_Objects']

In [39]:
print(SPs.keys())

<KeysViewHDF5 ['CH_on_MS(1)', 'CH_on_MS(2)', 'Eccentricity@ZAMS', 'Equilibrated_At_Birth', 'Error', 'Evolution_Status', 'Mass@ZAMS(1)', 'Mass@ZAMS(2)', 'Merger', 'Merger_At_Birth', 'Metallicity@ZAMS(1)', 'Metallicity@ZAMS(2)', 'Omega@ZAMS(1)', 'Omega@ZAMS(2)', 'PO_CE_Alpha', 'PO_CE_Formalism', 'PO_LBV_Factor', 'PO_Sigma_Kick_CCSN_BH', 'PO_Sigma_Kick_CCSN_NS', 'PO_Sigma_Kick_ECSN', 'PO_Sigma_Kick_USSN', 'PO_WR_Factor', 'Record_Type', 'SEED', 'SN_Kick_Magnitude_Random_Number(1)', 'SN_Kick_Magnitude_Random_Number(2)', 'SemiMajorAxis@ZAMS', 'Stellar_Type(1)', 'Stellar_Type(2)', 'Stellar_Type@ZAMS(1)', 'Stellar_Type@ZAMS(2)', 'Unbound']>

In [40]:
seedsSP = SPs['SEED'][()]
print(seedsSP)

[1789124407 1789124408 1789124409 1789124410 1789124411 1789124412
 1789124413 1789124414 1789124415 1789124416 1789124417 1789124418
 1789124419 1789124420 1789124421 1789124422 1789124423 1789124424
 1789124425 1789124426 1789124427 1789124428 1789124429 1789124430
 1789124431 1789124432 1789124433 1789124434 1789124435 1789124436
 1789124437 1789124438 1789124439 1789124440 1789124441 1789124442
 1789124443 1789124444 1789124445 1789124446 1789124447 1789124448
 1789124449 1789124450 1789124451 1789124452 1789124453 1789124454
 1789124455 1789124456 1789124457 1789124458 1789124459 1789124460
 1789124461 1789124462 1789124463 1789124464 1789124465 1789124466
 1789124467 1789124468 1789124469 1789124470 1789124471 1789124472
 1789124473 1789124474 1789124475 1789124476 1789124477 1789124478
 1789124479 1789124480 1789124481 1789124482 1789124483 1789124484
 1789124485 1789124486 1789124487 1789124488 1789124489 1789124490
 1789124491 1789124492 1789124493 1789124494 1789124495 1789124496
 1789124497 1789124498 1789124499 1789124500 1789124501 1789124502
 1789124503 1789124504 1789124505 1789124506 1789124507 1789124508
 1789124509 1789124510 1789124511 1789124512 1789124513 1789124514
 1789124515 1789124516 1789124517 1789124518 1789124519 1789124520
 1789124521 1789124522 1789124523 1789124524 1789124525 1789124526
 1789124527 1789124528 1789124529 1789124530 1789124531 1789124532
 1789124533 1789124534 1789124535 1789124536 1789124537 1789124538
 1789124539 1789124540 1789124541 1789124542 1789124543 1789124544
 1789124545 1789124546 1789124547 1789124548 1789124549 1789124550
 1789124551 1789124552 1789124553 1789124554 1789124555 1789124556
 1789124557 1789124558 1789124559 1789124560 1789124561 1789124562
 1789124563 1789124564 1789124565 1789124566 1789124567 1789124568
 1789124569 1789124570 1789124571 1789124572 1789124573 1789124574
 1789124575 1789124576 1789124577 1789124578 1789124579 1789124580
 1789124581 1789124582 1789124583 1789124584 1789124585 1789124586
 1789124587 1789124588 1789124589 1789124590 1789124591 1789124592
 1789124593 1789124594 1789124595 1789124596 1789124597 1789124598
 1789124599 1789124600 1789124601 1789124602 1789124603 1789124604
 1789124605 1789124606 1789124607 1789124608 1789124609 1789124610
 1789124611 1789124612 1789124613 1789124614 1789124615 1789124616
 1789124617 1789124618 1789124619 1789124620 1789124621 1789124622
 1789124623 1789124624 1789124625 1789124626 1789124627 1789124628
 1789124629 1789124630 1789124631 1789124632 1789124633 1789124634
 1789124635 1789124636 1789124637 1789124638 1789124639 1789124640
 1789124641 1789124642 1789124643 1789124644 1789124645 1789124646
 1789124647 1789124648 1789124649 1789124650 1789124651 1789124652
 1789124653 1789124654 1789124655 1789124656 1789124657 1789124658
 1789124659 1789124660 1789124661 1789124662 1789124663 1789124664
 1789124665 1789124666 1789124667 1789124668 1789124669 1789124670
 1789124671 1789124672 1789124673 1789124674 1789124675 1789124676
 1789124677 1789124678 1789124679 1789124680 1789124681 1789124682
 1789124683 1789124684 1789124685 1789124686 1789124687 1789124688
 1789124689 1789124690 1789124691 1789124692 1789124693 1789124694
 1789124695 1789124696 1789124697 1789124698 1789124699 1789124700
 1789124701 1789124702 1789124703 1789124704 1789124705 1789124706
 1789124707 1789124708 1789124709 1789124710 1789124711 1789124712
 1789124713 1789124714 1789124715 1789124716 1789124717 1789124718
 1789124719 1789124720 1789124721 1789124722 1789124723 1789124724
 1789124725 1789124726 1789124727 1789124728 1789124729 1789124730
 1789124731 1789124732 1789124733 1789124734 1789124735 1789124736
 1789124737 1789124738 1789124739 1789124740 1789124741 1789124742
 1789124743 1789124744 1789124745 1789124746 1789124747 1789124748
 1789124749 1789124750 1789124751 1789124752 1789124753 1789124754
 1789124755 1789124756 1789124757 1789124758 1789124759 1789124760
 1789124761 1789124762 1789124763 1789124764 1789124765 1789124766
 1789124767 1789124768 1789124769 1789124770 1789124771 1789124772
 1789124773 1789124774 1789124775 1789124776 1789124777 1789124778
 1789124779 1789124780 1789124781 1789124782 1789124783 1789124784
 1789124785 1789124786 1789124787 1789124788 1789124789 1789124790
 1789124791 1789124792 1789124793 1789124794 1789124795 1789124796
 1789124797 1789124798 1789124799 1789124800 1789124801 1789124802
 1789124803 1789124804 1789124805 1789124806 1789124807 1789124808
 1789124809 1789124810 1789124811 1789124812 1789124813 1789124814
 1789124815 1789124816 1789124817 1789124818 1789124819 1789124820
 1789124821 1789124822 1789124823 1789124824 1789124825 1789124826
 1789124827 1789124828 1789124829 1789124830 1789124831 1789124832
 1789124833 1789124834 1789124835 1789124836 1789124837 1789124838
 1789124839 1789124840 1789124841 1789124842 1789124843 1789124844
 1789124845 1789124846 1789124847 1789124848 1789124849 1789124850
 1789124851 1789124852 1789124853 1789124854 1789124855 1789124856
 1789124857 1789124858 1789124859 1789124860 1789124861 1789124862
 1789124863 1789124864 1789124865 1789124866 1789124867 1789124868
 1789124869 1789124870 1789124871 1789124872 1789124873 1789124874
 1789124875 1789124876 1789124877 1789124878 1789124879 1789124880
 1789124881 1789124882 1789124883 1789124884 1789124885 1789124886
 1789124887 1789124888 1789124889 1789124890 1789124891 1789124892
 1789124893 1789124894 1789124895 1789124896 1789124897 1789124898
 1789124899 1789124900 1789124901 1789124902 1789124903 1789124904
 1789124905 1789124906 1789124907 1789124908 1789124909 1789124910
 1789124911 1789124912 1789124913 1789124914 1789124915 1789124916
 1789124917 1789124918 1789124919 1789124920 1789124921 1789124922
 1789124923 1789124924 1789124925 1789124926 1789124927 1789124928
 1789124929 1789124930 1789124931 1789124932 1789124933 1789124934
 1789124935 1789124936 1789124937 1789124938 1789124939 1789124940
 1789124941 1789124942 1789124943 1789124944 1789124945 1789124946
 1789124947 1789124948 1789124949 1789124950 1789124951 1789124952
 1789124953 1789124954 1789124955 1789124956 1789124957 1789124958
 1789124959 1789124960 1789124961 1789124962 1789124963 1789124964
 1789124965 1789124966 1789124967 1789124968 1789124969 1789124970
 1789124971 1789124972 1789124973 1789124974 1789124975 1789124976
 1789124977 1789124978 1789124979 1789124980 1789124981 1789124982
 1789124983 1789124984 1789124985 1789124986 1789124987 1789124988
 1789124989 1789124990 1789124991 1789124992 1789124993 1789124994
 1789124995 1789124996 1789124997 1789124998 1789124999 1789125000
 1789125001 1789125002 1789125003 1789125004 1789125005 1789125006
 1789125007 1789125008 1789125009 1789125010 1789125011 1789125012
 1789125013 1789125014 1789125015 1789125016 1789125017 1789125018
 1789125019 1789125020 1789125021 1789125022 1789125023 1789125024
 1789125025 1789125026 1789125027 1789125028 1789125029 1789125030
 1789125031 1789125032 1789125033 1789125034 1789125035 1789125036
 1789125037 1789125038 1789125039 1789125040 1789125041 1789125042
 1789125043 1789125044 1789125045 1789125046 1789125047 1789125048
 1789125049 1789125050 1789125051 1789125052 1789125053 1789125054
 1789125055 1789125056 1789125057 1789125058 1789125059 1789125060
 1789125061 1789125062 1789125063 1789125064 1789125065 1789125066
 1789125067 1789125068 1789125069 1789125070 1789125071 1789125072
 1789125073 1789125074 1789125075 1789125076 1789125077 1789125078
 1789125079 1789125080 1789125081 1789125082 1789125083 1789125084
 1789125085 1789125086 1789125087 1789125088 1789125089 1789125090
 1789125091 1789125092 1789125093 1789125094 1789125095 1789125096
 1789125097 1789125098 1789125099 1789125100 1789125101 1789125102
 1789125103 1789125104 1789125105 1789125106 1789125107 1789125108
 1789125109 1789125110 1789125111 1789125112 1789125113 1789125114
 1789125115 1789125116 1789125117 1789125118 1789125119 1789125120
 1789125121 1789125122 1789125123 1789125124 1789125125 1789125126
 1789125127 1789125128 1789125129 1789125130 1789125131 1789125132
 1789125133 1789125134 1789125135 1789125136 1789125137 1789125138
 1789125139 1789125140 1789125141 1789125142 1789125143 1789125144
 1789125145 1789125146 1789125147 1789125148 1789125149 1789125150
 1789125151 1789125152 1789125153 1789125154 1789125155 1789125156
 1789125157 1789125158 1789125159 1789125160 1789125161 1789125162
 1789125163 1789125164 1789125165 1789125166 1789125167 1789125168
 1789125169 1789125170 1789125171 1789125172 1789125173 1789125174
 1789125175 1789125176 1789125177 1789125178 1789125179 1789125180
 1789125181 1789125182 1789125183 1789125184 1789125185 1789125186
 1789125187 1789125188 1789125189 1789125190 1789125191 1789125192
 1789125193 1789125194 1789125195 1789125196 1789125197 1789125198
 1789125199 1789125200 1789125201 1789125202 1789125203 1789125204
 1789125205 1789125206 1789125207 1789125208 1789125209 1789125210
 1789125211 1789125212 1789125213 1789125214 1789125215 1789125216
 1789125217 1789125218 1789125219 1789125220 1789125221 1789125222
 1789125223 1789125224 1789125225 1789125226 1789125227 1789125228
 1789125229 1789125230 1789125231 1789125232 1789125233 1789125234
 1789125235 1789125236 1789125237 1789125238 1789125239 1789125240
 1789125241 1789125242 1789125243 1789125244 1789125245 1789125246
 1789125247 1789125248 1789125249 1789125250 1789125251 1789125252
 1789125253 1789125254 1789125255 1789125256 1789125257 1789125258
 1789125259 1789125260 1789125261 1789125262 1789125263 1789125264
 1789125265 1789125266 1789125267 1789125268 1789125269 1789125270
 1789125271 1789125272 1789125273 1789125274 1789125275 1789125276
 1789125277 1789125278 1789125279 1789125280 1789125281 1789125282
 1789125283 1789125284 1789125285 1789125286 1789125287 1789125288
 1789125289 1789125290 1789125291 1789125292 1789125293 1789125294
 1789125295 1789125296 1789125297 1789125298 1789125299 1789125300
 1789125301 1789125302 1789125303 1789125304 1789125305 1789125306
 1789125307 1789125308 1789125309 1789125310 1789125311 1789125312
 1789125313 1789125314 1789125315 1789125316 1789125317 1789125318
 1789125319 1789125320 1789125321 1789125322 1789125323 1789125324
 1789125325 1789125326 1789125327 1789125328 1789125329 1789125330
 1789125331 1789125332 1789125333 1789125334 1789125335 1789125336
 1789125337 1789125338 1789125339 1789125340 1789125341 1789125342
 1789125343 1789125344 1789125345 1789125346 1789125347 1789125348
 1789125349 1789125350 1789125351 1789125352 1789125353 1789125354
 1789125355 1789125356 1789125357 1789125358 1789125359 1789125360
 1789125361 1789125362 1789125363 1789125364 1789125365 1789125366
 1789125367 1789125368 1789125369 1789125370 1789125371 1789125372
 1789125373 1789125374 1789125375 1789125376 1789125377 1789125378
 1789125379 1789125380 1789125381 1789125382 1789125383 1789125384
 1789125385 1789125386 1789125387 1789125388 1789125389 1789125390
 1789125391 1789125392 1789125393 1789125394 1789125395 1789125396
 1789125397 1789125398 1789125399 1789125400 1789125401 1789125402
 1789125403 1789125404 1789125405 1789125406]

In [41]:
printCompasDetails(SPs)

SEED,(units),1789124407,1789124408,1789124409,1789124410,1789124411,1789124412,1789124413,1789124414,1789124415,...,1789125397,1789125398,1789125399,1789125400,1789125401,1789125402,1789125403,1789125404,1789125405,1789125406
CH_on_MS(1),State,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
CH_on_MS(2),State,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Eccentricity@ZAMS,-,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Equilibrated_At_Birth,Event,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Error,-,43.000000,0.000000,0.000000,0.000000,0.000000,43.000000,0.000000,0.000000,0.000000,...,43.000000,43.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,43.000000
Evolution_Status,-,3.000000,3.000000,15.000000,3.000000,3.000000,12.000000,17.000000,15.000000,3.000000,...,3.000000,15.000000,15.000000,3.000000,15.000000,3.000000,15.000000,15.000000,15.000000,15.000000
Mass@ZAMS(1),Msol,1.092116,1.226874,1.672555,1.144794,1.141747,2.480340,16.919259,3.486440,1.242156,...,1.554448,3.404113,1.424387,1.290934,3.549636,1.017087,3.086798,3.683443,4.005721,1.025259
Mass@ZAMS(2),Msol,0.685395,0.611163,1.142072,0.141469,0.505610,0.368976,8.058986,1.280110,0.022830,...,0.374386,1.339532,1.176928,0.087130,2.652593,0.807781,1.585211,2.025736,3.896115,0.955077
Merger,Event,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Merger_At_Birth,Event,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Metallicity@ZAMS(1),-,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,...,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200
Metallicity@ZAMS(2),-,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,...,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200,0.014200
Omega@ZAMS(1),Hz,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Omega@ZAMS(2),Hz,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
PO_CE_Alpha,-,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
PO_CE_Formalism,-,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
PO_LBV_Factor,-,1.500000,1.500000,1.500000,1.500000,1.500000,1.500000,1.500000,1.500000,1.500000,...,1.500000,1.500000,1.500000,1.500000,1.500000,1.500000,1.500000,1.500000,1.500000,1.500000
PO_Sigma_Kick_CCSN_BH,kms^-1,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,...,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000
PO_Sigma_Kick_CCSN_NS,kms^-1,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,...,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000,217.000000
PO_Sigma_Kick_ECSN,kms^-1,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
PO_Sigma_Kick_USSN,kms^-1,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
PO_WR_Factor,-,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
Record_Type,-,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
SN_Kick_Magnitude_Random_Number(1),-,0.596163,0.593535,0.404596,0.637350,0.884968,0.700130,0.346214,0.445343,0.502016,...,0.726689,0.012525,0.980089,0.092933,0.121849,0.969969,0.594418,0.325357,0.944486,0.885831
SN_Kick_Magnitude_Random_Number(2),-,0.443395,0.129016,0.916996,0.733555,0.856061,0.500782,0.745376,0.754353,0.746915,...,0.895319,0.819694,0.273065,0.518662,0.025205,0.711947,0.944582,0.710494,0.938599,0.582750
SemiMajorAxis@ZAMS,AU,0.397944,742.802022,105.752896,4.995709,80.937710,0.052969,151.760554,10.629528,26.095462,...,1.890968,0.166209,0.777429,11.955900,73.884898,0.661945,589.453850,53.009489,15.781258,0.859216
Stellar_Type(1),-,10.000000,11.000000,11.000000,11.000000,11.000000,2.000000,13.000000,11.000000,11.000000,...,11.000000,11.000000,10.000000,11.000000,11.000000,10.000000,11.000000,11.000000,11.000000,10.000000
Stellar_Type(2),-,0.000000,0.000000,11.000000,0.000000,0.000000,0.000000,13.000000,11.000000,0.000000,...,0.000000,10.000000,11.000000,0.000000,11.000000,1.000000,11.000000,11.000000,11.000000,11.000000
Stellar_Type@ZAMS(1),-,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
Stellar_Type@ZAMS(2),-,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
Unbound,State,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [42]:
printCompasDetails(SNe)

SEED,(units),1789124413,1789124413,1789124424,1789124439,1789124452,1789124452,1789124466,1789124490,1789124490,...,1789125290,1789125297,1789125298,1789125348,1789125352,1789125361,1789125361,1789125376,1789125386,1789125386
Applied_Kick_Magnitude(SN),kms^-1,1007.055509,177.680229,200.676842,0.0,0.0,0.0,172.29494,0.0,0.0,...,168.811769,873.807805,0.180675,604.873963,0.0,38.077637,350.822929,209.046952,0.0,970.91119
ComponentSpeed(CP),kms^-1,7.19693,1004.712748,6.689378,0.0,0.0,0.853308,10.100067,0.0,0.0,...,5.975016,20.91267,0.210727,18.773596,2.390999,21.454397,155.931366,31.184775,0.0,132.889615
ComponentSpeed(SN),kms^-1,1004.712748,171.764566,204.953389,0.0,0.0,0.853308,179.420875,0.0,0.0,...,171.262633,867.271106,0.210727,568.319695,0.108532,21.454397,155.931366,146.519991,0.0,981.957417
Drawn_Kick_Magnitude(SN),kms^-1,1007.055509,177.680229,200.676842,0.0,0.0,0.0,172.29494,0.0,0.0,...,168.811769,873.807805,0.180675,604.873963,0.0,38.077637,350.822929,209.046952,0.0,970.91119
Eccentricity,-,15697.027991,15697.027991,682.341829,0.0,0.0,0.752991,145.240095,0.0,0.0,...,896.101819,2242.41172,0.00015,124.527188,1.522811,0.219155,0.92323,1.297569,0.0,2.756948
Eccentricity<SN,-,0.0,15697.027991,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Experienced_RLOF(SN),Event,0,0,0,1,0,0,0,1,0,...,0,0,1,1,0,1,1,1,0,1
Fallback_Fraction(SN),-,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Is_Hydrogen_Poor(SN),State,0,0,0,1,1,0,0,1,1,...,0,0,1,1,0,1,1,1,1,1
MT_Donor_Hist(SN),-,b'NA ',b'NA ',b'NA ',b'1-2 ',b'NA ',b'NA ',b'NA ',b'1-2 ',b'NA ',...,b'NA ',b'NA ',b'4-8 ',b'2 ',b'NA ',b'2 ',b'2 ',b'2 ',b'NA ',b'4 '
Mass(CP),Msol,8.054441,1.403585,4.595763,65.347558,26.21591,10.213156,3.822333,93.06334,11.949539,...,3.528216,4.998257,1.071743,5.498982,0.388307,15.01607,4.315046,7.048012,19.318594,10.132311
Mass(SN),Msol,1.403585,1.183671,1.182371,10.24501,10.213156,10.020225,1.177082,11.949539,12.397871,...,1.210048,1.427815,2.50099,1.187735,7.052718,4.314899,1.666759,1.213967,10.132311,1.505182
Mass_CO_Core@CO(SN),Msol,4.098883,1.440128,1.440016,7.747712,7.724367,7.752074,1.44,9.077554,9.418217,...,1.440231,3.432178,2.502898,1.80008,5.332688,5.085143,2.527511,1.590424,7.635192,3.855265
Mass_Core@CO(SN),Msol,5.733576,1.440128,1.440016,7.747712,7.724367,10.020225,1.44,9.077554,9.418217,...,1.440231,4.890164,2.502898,1.80008,7.052718,5.085143,2.527511,1.590424,7.635192,3.855265
Mass_He_Core@CO(SN),Msol,5.733576,1.440128,1.440016,10.24501,10.213156,10.020225,1.44,11.949539,12.397871,...,1.440231,4.890164,2.502898,2.768218,7.052718,6.983232,3.701896,2.503011,10.132311,5.404447
Mass_Total@CO(SN),Msol,14.878353,7.417285,6.778526,10.24501,10.213156,25.255778,4.384882,11.949539,12.397871,...,7.693029,13.116104,2.502898,2.768218,18.383991,6.983232,3.701896,2.503011,10.132311,5.404447
Orb_Velocity<SN,kms^-1,11.088784,0.0,11.31591,289.392017,4.04225,3.935538,19.606575,240.503052,49.626972,...,8.814012,28.73958,563.159165,54.337798,5.246885,156.515012,247.594046,120.340552,61.910812,666.500096
Orbital_AM_Vector>SN_X,-,0.406711,0.406711,-0.021322,-0.0,0.0,0.0,0.200038,0.0,0.0,...,-0.009562,0.213542,-0.000023,0.00815,0.0,0.11707,0.0,-0.114857,0.0,0.0
Orbital_AM_Vector>SN_Y,-,0.542511,0.542511,0.011064,0.0,0.0,0.0,-0.25917,0.0,-0.0,...,0.000832,0.465785,0.000004,-0.370172,0.0,-0.105911,0.982366,-0.112349,0.0,-0.071624
Orbital_AM_Vector>SN_Z,-,-0.735029,-0.735029,0.999711,1.0,1.0,1.0,0.944889,1.0,1.0,...,0.999954,-0.858746,1.0,-0.928927,1.0,0.98746,-0.18697,0.987008,1.0,0.997432
Radius_Core@CO(SN),Rsol,2.934808,0.000071,0.000071,0.000071,0.000071,1.190679,0.000071,0.000071,0.000071,...,0.000071,13.969741,0.000014,0.000071,1.192599,0.000071,0.000071,0.000071,0.000071,0.000071
Radius_Total@CO(SN),Rsol,1136.352525,653.152744,972.012931,1.095059,1.094559,1479.17119,1147.910237,1.143146,1.156475,...,553.504739,1137.28529,0.000014,13.785374,1113.764114,1.117455,5.69124,14.533101,1.086117,1.666106
Record_Type,-,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
SN_Kick_Mean_Anomaly(SN),-,5.639887,1.464885,1.092146,4.856457,1.761474,4.869142,3.798928,2.098725,0.552532,...,4.625645,2.711729,1.410048,0.022013,3.653323,3.976991,5.190085,2.345157,4.407142,4.275809
SN_Kick_Phi(SN),-,4.863415,3.001948,2.514958,0.274426,2.045039,1.352064,5.739581,1.429332,0.892095,...,0.283343,0.66318,0.310514,4.966328,1.714482,1.786049,4.034619,2.103449,5.017597,2.93947
SN_Kick_Theta(SN),-,-0.565331,0.013365,-0.025116,-0.009522,-1.028077,-0.426118,-0.35,-0.324235,0.355547,...,0.00945,0.469919,-0.07289,0.336659,-0.536065,-0.580386,-0.25506,-0.05483,-0.108542,0.063724
SN_Orbit_Inclination_Angle,-,2.396506,2.396506,0.024024,0.0,0.0,0.0,0.33354,0.0,0.0,...,0.009599,2.603613,0.000023,2.762302,0.0,0.158532,1.758873,0.161368,0.0,0.071686
SN_Type(SN),-,1,1,1,1,1,1,1,1,1,...,1,1,16,1,1,1,1,1,1,1
SemiMajorAxis,Rsol,-1.801781,-1.933555,-24.616196,172.11834,425131.031996,1767860.750806,-26.839763,346.196382,1885.117149,...,-28.881665,-1.692468,2.149194,-4.198934,-248708.625884,146.183009,29.977822,-74.656031,1465.165835,-2.262776
SemiMajorAxis<SN,Rsol,35563.973924,-1.933555,16938.166977,172.11834,425131.031996,436677.706924,4071.116247,346.196382,1885.117149,...,27543.235573,4181.993365,2.149272,533.919148,130027.562368,171.245061,24.937301,125.761304,1465.165835,6.669313
Stellar_Type(CP),-,1,13,1,1,1,14,1,1,14,...,1,1,11,1,0,1,14,1,1,14
Stellar_Type(SN),-,13,13,13,14,14,14,13,14,14,...,13,13,14,13,14,14,13,13,14,13
Stellar_Type_Prev(SN),-,5,6,6,8,8,5,6,8,8,...,6,5,8,8,5,8,8,8,8,8
Supernova_State,State,1,2,1,1,1,2,1,1,2,...,1,1,2,1,1,1,2,1,1,2
SystemicSpeed,kms^-1,152.797313,152.797313,36.691793,0.0,0.0,0.853308,35.546826,0.0,0.0,...,39.599676,205.761339,0.210727,115.338188,0.165274,21.454397,155.931366,36.590641,0.0,172.196713
SystemicVelocityX,kms^-1,15.658255,15.658255,-29.321236,0.0,0.0,0.236055,29.033474,0.0,0.0,...,37.612439,142.42613,0.209141,25.66409,-0.080933,-12.453641,-56.808487,-5.670209,0.0,-168.811391
SystemicVelocityY,kms^-1,-129.199097,-129.199097,22.033823,0.0,0.0,-0.820008,-15.071426,0.0,0.0,...,12.380339,119.680783,0.024106,-106.698591,0.144103,16.836768,137.784133,36.109419,0.0,-33.022316
SystemicVelocityZ,kms^-1,-80.058923,-80.058923,-1.031243,0.0,0.0,0.0,-13.909937,0.0,0.0,...,0.40739,87.914937,-0.009211,35.491727,0.0,-4.660603,-45.857599,-1.683331,0.0,7.996817
Time,Myr,12.489547,42.359204,43.723564,4.83731,5.122368,7.481728,43.905,4.122801,5.412705,...,41.791381,14.819135,43.231374,21.011134,10.138507,8.033914,17.553382,23.603348,4.905073,10.589125
Unbound,State,1,1,1,0,0,0,1,0,0,...,1,1,0,1,1,0,0,1,0,1

In [43]:
printCompasDetails(DCs)

SEED,(units),1789124452,1789124490,1789124670,1789124694,1789124712,1789124821,1789124885,1789125361
Coalescence_Time,Myr,3.853900e+22,5.264905e+11,6.607963e+14,1.821187e+07,1.716591e+14,1.996291e+19,1.187005e+05,4148.626352
Eccentricity@DCO,-,7.529909e-01,4.002966e-16,2.220446e-16,5.464043e-01,7.399584e-01,7.781822e-01,2.220446e-16,0.923230
Mass(1),Msol,1.021316e+01,1.194954e+01,9.229741e+00,9.766587e+00,8.593491e+00,1.005704e+01,1.017497e+01,4.315046
Mass(2),Msol,1.002023e+01,1.239787e+01,1.518981e+01,4.388711e+00,9.223552e+00,1.105039e+01,9.974353e+00,1.666759
Merges_Hubble_Time,State,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
Record_Type,-,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000
Recycled_NS(1),Event,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
Recycled_NS(2),Event,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
SemiMajorAxis@DCO,AU,8.221379e+03,8.766676e+00,5.150346e+01,5.871178e-01,5.877456e+01,1.385978e+03,1.657610e-01,0.139411
Stellar_Type(1),-,1.400000e+01,1.400000e+01,1.400000e+01,1.400000e+01,1.400000e+01,1.400000e+01,1.400000e+01,14.000000
Stellar_Type(2),-,1.400000e+01,1.400000e+01,1.400000e+01,1.400000e+01,1.400000e+01,1.400000e+01,1.400000e+01,13.000000
Time,Myr,7.481728e+00,5.412705e+00,7.222037e+00,8.507774e+00,9.146259e+00,6.947609e+00,7.531914e+00,17.553382

In [16]:
seeds, events = getEventHistory(Data)

for ii, seed in enumerate(seeds):
    print(seed, events[ii])

eventStrings = getEventStrings(allEvents=events)
for ii in range(5):
    print(seeds[ii], eventStrings[ii])

1789121747 [('SN', np.float64(16.679503858169653), np.int32(5), np.int32(13), np.int32(2), np.True_), ('SN', np.float64(37.85974454113952), np.int32(5), np.int32(13), np.int32(1), np.True_)]
1789121748 [('SN', np.float64(10.122723092530407), np.int32(5), np.int32(14), np.int32(1), np.False_), ('SN', np.float64(14.620375474195676), np.int32(5), np.int32(13), np.int32(2), np.True_)]
1789121749 []
1789121750 [('SN', np.float64(5.149318958027189), np.int32(5), np.int32(14), np.int32(2), np.False_), ('SN', np.float64(5.70009718442838), np.int32(5), np.int32(14), np.int32(1), np.False_)]
1789121751 [('MT', np.float64(21.463676870679432), np.int32(4), np.int32(1), np.True_, np.False_, np.False_), ('SN', np.float64(21.63748617499244), np.int32(8), np.int32(13), np.int32(1), np.True_), ('SN', np.float64(29.00375575601476), np.int32(5), np.int32(13), np.int32(2), np.True_)]
1789121747 13*U5_5*U13
1789121748 5*I14_13*U5
1789121749 NA
1789121750 14*I5_5*I14
1789121751 4>1_8*U13_13*U5

In [9]:
# Available groups
for group_name in f.keys():
    print(group_name)

NameError: name 'f' is not defined

In [10]:
# Load a group function
def load_group(h5file, group_name):
    group = h5file[group_name]
    return pd.DataFrame({col: group[col][()] for col in group.keys()})

In [ ]:
# Load the group
SN = load_group(f, 'BSE_Supernovae')  # BSE_Supernovae
print(SN)

In [ ]:
system = load_group(f, 'BSE_System_Parameters')
print(system)

In [ ]:
double_compact_objects = load_group(f, 'BSE_Double_Compact_Objects')
print(double_compact_objects)

In [ ]:
f = h5py.File('COMPAS_Output.h5', 'r')
group = f['BSE_System_Parameters']
df = pd.DataFrame({key: group[key][()] for key in group.keys()})
df.head()